'''Lets play with radio buttons!'''

from tkinter import *

#For this example we will use a list of items
drinks = ["Wine", "Beer", "Water?"]     #create list containing items Wine, Beer and Water

def order():
    if(x.get()==0):
        print("You ordered Wine")
    elif(x.get()==1):
        print("You ordered Beer")
    elif(x.get()==2):
        print("You ordered water? Err ok")
    else:
        print("huh?")
window_01 = Tk()     #Create window

#Some pictures to use in the radio button program
wineImage = PhotoImage(file='funny_pictures/wine_bottle.png')
beerImage = PhotoImage(file='funny_pictures/beer_glass.png')
waterImage = PhotoImage(file='funny_pictures/water_glass.png')
#And a list to store the PhotoImages in
drinksImages = [wineImage,beerImage,waterImage]

x = IntVar()
'''
To create a radio button for each entry in the list, we will use a for loop
for each index(item) in range(list) length of drinks list
'''
for index in range(len(drinks)):
    radio_button_01 = Radiobutton(window_01,            #Place each button generated by for loop in window_01 container
                                  text=drinks[index],    #assign each button generated the index name (Wine, beer, Water?)
                                  variable=x,           #groups radio buttons together if they share the same variable
                                  value=index,           #assign each radio button a different value equal to the index of its item
                                  padx = 25,             #adds padding on x-axis
                                  font=("Impact", 50),   #Set font of text of radio buttons
                                  image = drinksImages[index],   #Adds image to radio button
                                  compound = 'left',     #add image to left of text
                                  indicatoron=0,         #eliminate circle indicators
                                  width = 375,           #sets width of radio buttons
                                  command=order         #set command to order function
                                  )

    radio_button_01.pack(anchor=W)      #pack all the buttons into the window. Anchor(place) on the west side of the window.


window_01.mainloop()    #Display window_01 and all its contents